#!/bin/bash
lasttxid=$(cat pendingold | jq .tx | tail --lines 1)

doprint=false
foundprev=false
prevline=""

while read line
do
  if $doprint ; then
    echo "$line"
  fi
  if $foundprev ; then
    if [ "$line" = "}" ]; then
      doprint=true
    fi       
  fi
  if [[ "$line" == *"$lasttxid"* ]]; then
    foundprev=true
  fi
  prevline=$line
done
