#!/bin/bash

blocknum=0

while true
do
  newnum=$(./getcurrblock)
  if [ $blocknum -lt $newnum ]
  then
    blocknum=$newnum    
    inp=$( goal ledger block --strict $blocknum )
    cd ..
	while IFS= read -r line
	do
	  if [[ $line != \#* ]] ; then
	    echo "$inp" | ( eval "$line" )
	  fi
	done < ./pipelines
	cd app
  fi
  
  sleep 1
done
